# Form implementation generated from reading ui file 'ui/scOrganizar.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        MainWindow.setMinimumSize(QtCore.QSize(960, 540))
        MainWindow.setMaximumSize(QtCore.QSize(960, 540))
        MainWindow.setStyleSheet("\n"
"background-color: rgb(249, 250, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(960, 540))
        self.centralwidget.setMaximumSize(QtCore.QSize(960, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuLateral = QtWidgets.QFrame(parent=self.frame_2)
        self.menuLateral.setMinimumSize(QtCore.QSize(50, 0))
        self.menuLateral.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menuLateral.setStyleSheet("background-color: rgb(203, 209, 221);")
        self.menuLateral.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.menuLateral.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuLateral.setObjectName("menuLateral")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menuLateral)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(parent=self.menuLateral)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.btnMenuLargo = QtWidgets.QPushButton(parent=self.frame_5)
        self.btnMenuLargo.setGeometry(QtCore.QRect(0, 0, 200, 65))
        self.btnMenuLargo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMenuLargo.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"background:transparent;\n"
"padding:10px;\n"
"text-align:left;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(214, 214, 214);\n"
"\n"
"}")
        self.btnMenuLargo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/login/user.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMenuLargo.setIcon(icon)
        self.btnMenuLargo.setIconSize(QtCore.QSize(30, 30))
        self.btnMenuLargo.setObjectName("btnMenuLargo")
        self.lblCurso = QtWidgets.QLabel(parent=self.frame_5)
        self.lblCurso.setGeometry(QtCore.QRect(50, 20, 141, 21))
        self.lblCurso.setAutoFillBackground(False)
        self.lblCurso.setStyleSheet("background:transparent;\n"
"font: 8pt \"Helvetica Light\";\n"
"")
        self.lblCurso.setObjectName("lblCurso")
        self.lblNome = QtWidgets.QLabel(parent=self.frame_5)
        self.lblNome.setGeometry(QtCore.QRect(50, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica Rounded")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lblNome.setFont(font)
        self.lblNome.setStyleSheet("background: transparent;\n"
"font: 75 10pt \"Helvetica Rounded\";\n"
"color: black;")
        self.lblNome.setObjectName("lblNome")
        self.btnPerfil = QtWidgets.QPushButton(parent=self.frame_5)
        self.btnPerfil.setGeometry(QtCore.QRect(50, 40, 61, 16))
        self.btnPerfil.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPerfil.setStyleSheet("QPushButton{\n"
"    background:transparent;\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    color:white;\n"
"\n"
"}")
        self.btnPerfil.setObjectName("btnPerfil")
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.menuLateral)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.btnTarefas = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnTarefas.setGeometry(QtCore.QRect(0, 20, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnTarefas.setFont(font)
        self.btnTarefas.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnTarefas.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"background:transparent;\n"
"padding:10px;\n"
"text-align:left;\n"
"font: 75 10pt \"Helvetica\";\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/img/icon/task.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/iconActive/img/icon/iconActive/task2.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.btnTarefas.setIcon(icon1)
        self.btnTarefas.setIconSize(QtCore.QSize(30, 30))
        self.btnTarefas.setCheckable(True)
        self.btnTarefas.setObjectName("btnTarefas")
        self.btnMatriz = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnMatriz.setGeometry(QtCore.QRect(0, 120, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnMatriz.setFont(font)
        self.btnMatriz.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMatriz.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"background:transparent;\n"
"padding:10px;\n"
"text-align:left;\n"
"font: 75 10pt \"Helvetica\";\n"
"\n"
"\n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/img/icon/matrix.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/iconActive/img/icon/iconActive/matrix2.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.btnMatriz.setIcon(icon2)
        self.btnMatriz.setIconSize(QtCore.QSize(30, 30))
        self.btnMatriz.setCheckable(True)
        self.btnMatriz.setObjectName("btnMatriz")
        self.btnPomodoro = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnPomodoro.setGeometry(QtCore.QRect(0, 70, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnPomodoro.setFont(font)
        self.btnPomodoro.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPomodoro.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"background:transparent;\n"
"padding:10px;\n"
"text-align:left;\n"
"font: 75 10pt \"Helvetica\";\n"
"\n"
"\n"
"}\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/img/icon/pomodoro-technique.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/iconActive/img/icon/iconActive/pomodoro2.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.btnPomodoro.setIcon(icon3)
        self.btnPomodoro.setIconSize(QtCore.QSize(30, 30))
        self.btnPomodoro.setCheckable(True)
        self.btnPomodoro.setObjectName("btnPomodoro")
        self.btnCalendario = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnCalendario.setGeometry(QtCore.QRect(0, 170, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnCalendario.setFont(font)
        self.btnCalendario.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCalendario.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"background:transparent;\n"
"padding:10px;\n"
"text-align:left;\n"
"font: 75 10pt \"Helvetica\";\n"
"\n"
"\n"
"}\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/img/icon/calendar-silhouette.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(":/iconActive/img/icon/iconActive/calendar-silhouette2.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.btnCalendario.setIcon(icon4)
        self.btnCalendario.setIconSize(QtCore.QSize(30, 30))
        self.btnCalendario.setCheckable(True)
        self.btnCalendario.setObjectName("btnCalendario")
        self.btnDesempenho = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnDesempenho.setGeometry(QtCore.QRect(0, 220, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnDesempenho.setFont(font)
        self.btnDesempenho.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnDesempenho.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"background:transparent;\n"
"padding:10px;\n"
"text-align:left;\n"
"font: 75 10pt \"Helvetica\";\n"
"\n"
"\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/img/icon/line-chart.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5.addPixmap(QtGui.QPixmap(":/iconActive/img/icon/iconActive/line-chart2.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.btnDesempenho.setIcon(icon5)
        self.btnDesempenho.setIconSize(QtCore.QSize(30, 30))
        self.btnDesempenho.setCheckable(True)
        self.btnDesempenho.setObjectName("btnDesempenho")
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout_2.addWidget(self.menuLateral)
        self.telas = QtWidgets.QFrame(parent=self.frame_2)
        self.telas.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.telas.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.telas.setObjectName("telas")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.telas)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.paginas = QtWidgets.QStackedWidget(parent=self.telas)
        self.paginas.setObjectName("paginas")
        self.pgTarefas = QtWidgets.QWidget()
        self.pgTarefas.setObjectName("pgTarefas")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pgTarefas)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(parent=self.pgTarefas)
        self.widget.setObjectName("widget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 70))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.label = QtWidgets.QLabel(parent=self.widget_5)
        self.label.setGeometry(QtCore.QRect(80, 20, 151, 31))
        self.label.setStyleSheet("QLabel {\n"
"    color: #2e2e2e;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 28pt;\n"
"    font-weight: bold;\n"
"    qproperty-alignment: AlignCenter;\n"
"\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3.addWidget(self.widget_6)
        self.verticalLayout_9.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_7.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_7.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_7.setObjectName("widget_7")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 151, 16))
        self.label_6.setStyleSheet("QLabel {\n"
"    color: #444;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    padding-left: 4px;\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.txtTask = QtWidgets.QLineEdit(parent=self.widget_7)
        self.txtTask.setGeometry(QtCore.QRect(10, 60, 271, 41))
        self.txtTask.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid rgb(200, 200, 200);\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 12pt;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(134, 225, 140);\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"")
        self.txtTask.setText("")
        self.txtTask.setObjectName("txtTask")
        self.btnAddTask = QtWidgets.QPushButton(parent=self.widget_7)
        self.btnAddTask.setGeometry(QtCore.QRect(30, 130, 241, 51))
        self.btnAddTask.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnAddTask.setStyleSheet("QPushButton {\n"
"    background-color: rgb(134, 225, 140);\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    border-radius: 20px;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(111, 212, 104);\n"
"}\n"
"")
        self.btnAddTask.setObjectName("btnAddTask")
        self.btnDeleteTask = QtWidgets.QPushButton(parent=self.widget_7)
        self.btnDeleteTask.setGeometry(QtCore.QRect(30, 250, 241, 51))
        self.btnDeleteTask.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnDeleteTask.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 89, 89);\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    border-radius: 20px;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(225, 67, 67);\n"
"}\n"
"")
        self.btnDeleteTask.setObjectName("btnDeleteTask")
        self.btnCleanTaskList = QtWidgets.QPushButton(parent=self.widget_7)
        self.btnCleanTaskList.setGeometry(QtCore.QRect(60, 310, 171, 41))
        self.btnCleanTaskList.setStyleSheet("QPushButton {\n"
"    background-color: rgb(199, 199, 199);\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    border-radius: 20px;\n"
"    padding: 6px 14px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(160, 160, 160);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(130, 130, 130);\n"
"}\n"
"")
        self.btnCleanTaskList.setObjectName("btnCleanTaskList")
        self.btnEditTask = QtWidgets.QPushButton(parent=self.widget_7)
        self.btnEditTask.setGeometry(QtCore.QRect(30, 190, 241, 51))
        self.btnEditTask.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnEditTask.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 150, 255);\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    border-radius: 20px;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 0, 255);\n"
"}\n"
"")
        self.btnEditTask.setObjectName("btnEditTask")
        self.horizontalLayout_4.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.taskList = QtWidgets.QListWidget(parent=self.widget_8)
        self.taskList.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.taskList.setStyleSheet("QListWidget {\n"
"    border: none;\n"
"    border-left: 3px solid rgb(200, 200, 200);\n"
"    border-top: 3px solid rgb(200, 200, 200);\n"
"    background-color: rgb(245, 245, 245);\n"
"    padding: 5px;\n"
"    border-top-left-radius: 10px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    border: 1px solid rgb(220, 220, 220);\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    margin: 4px 0;\n"
"    background-color: white;\n"
"    color: #333;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: rgb(235, 235, 235);\n"
"    border: 1px solid rgb(180, 180, 180);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(200, 220, 255);\n"
"    border: 1px solid rgb(100, 150, 200);\n"
"    color: black;\n"
"}\n"
"")
        self.taskList.setTabKeyNavigation(False)
        self.taskList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.taskList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerItem)
        self.taskList.setMovement(QtWidgets.QListView.Movement.Static)
        self.taskList.setFlow(QtWidgets.QListView.Flow.TopToBottom)
        self.taskList.setLayoutMode(QtWidgets.QListView.LayoutMode.SinglePass)
        self.taskList.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.taskList.setModelColumn(0)
        self.taskList.setObjectName("taskList")
        self.verticalLayout_10.addWidget(self.taskList)
        self.horizontalLayout_4.addWidget(self.widget_8)
        self.verticalLayout_9.addWidget(self.widget_3)
        self.verticalLayout_4.addWidget(self.widget)
        self.paginas.addWidget(self.pgTarefas)
        self.pgPomodoro = QtWidgets.QWidget()
        self.pgPomodoro.setObjectName("pgPomodoro")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pgPomodoro)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_9 = QtWidgets.QWidget(parent=self.pgPomodoro)
        self.widget_9.setObjectName("widget_9")
        self.widget_10 = QtWidgets.QWidget(parent=self.widget_9)
        self.widget_10.setGeometry(QtCore.QRect(240, 100, 411, 321))
        self.widget_10.setStyleSheet("image: url(:/img/img/pomodoro.png);")
        self.widget_10.setObjectName("widget_10")
        self.lblTimer = QtWidgets.QLabel(parent=self.widget_10)
        self.lblTimer.setGeometry(QtCore.QRect(0, 140, 411, 101))
        self.lblTimer.setStyleSheet("background: transparent;\n"
"color: white;\n"
"font: 75 32pt \"MS Shell Dlg 2\";\n"
"qproperty-alignment: AlignCenter;\n"
"")
        self.lblTimer.setObjectName("lblTimer")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_9)
        self.label_2.setGeometry(QtCore.QRect(336, 29, 241, 41))
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #2e2e2e;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 28pt;\n"
"    font-weight: bold;\n"
"    qproperty-alignment: AlignCenter;\n"
"\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.btnStart = QtWidgets.QPushButton(parent=self.widget_9)
        self.btnStart.setGeometry(QtCore.QRect(370, 450, 161, 41))
        self.btnStart.setStyleSheet("QPushButton {\n"
"    background-color: #28a745;\n"
"    color: white;\n"
"    font: bold 14pt \"Segoe UI\";\n"
"    border-radius: 18px;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #218838;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e7e34;\n"
"}\n"
"")
        self.btnStart.setObjectName("btnStart")
        self.verticalLayout_5.addWidget(self.widget_9)
        self.paginas.addWidget(self.pgPomodoro)
        self.pgMatriz = QtWidgets.QWidget()
        self.pgMatriz.setObjectName("pgMatriz")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pgMatriz)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(parent=self.pgMatriz)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.paginas.addWidget(self.pgMatriz)
        self.pgCalendario = QtWidgets.QWidget()
        self.pgCalendario.setObjectName("pgCalendario")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pgCalendario)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(parent=self.pgCalendario)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.paginas.addWidget(self.pgCalendario)
        self.pgDesempenho = QtWidgets.QWidget()
        self.pgDesempenho.setObjectName("pgDesempenho")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pgDesempenho)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(parent=self.pgDesempenho)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.paginas.addWidget(self.pgDesempenho)
        self.verticalLayout_3.addWidget(self.paginas)
        self.horizontalLayout_2.addWidget(self.telas)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.paginas.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tela Organizar"))
        self.lblCurso.setText(_translate("MainWindow", "Curso Teste preencher"))
        self.lblNome.setText(_translate("MainWindow", "Nome do Usuario"))
        self.btnPerfil.setText(_translate("MainWindow", "Exibir Perfil"))
        self.btnTarefas.setText(_translate("MainWindow", "   Tarefas"))
        self.btnMatriz.setText(_translate("MainWindow", "   Matriz de Eisenhower"))
        self.btnPomodoro.setText(_translate("MainWindow", "   Pomodoro"))
        self.btnCalendario.setText(_translate("MainWindow", "   Calendário"))
        self.btnDesempenho.setText(_translate("MainWindow", "   Desempenho"))
        self.label.setText(_translate("MainWindow", "Tarefas"))
        self.label_6.setText(_translate("MainWindow", "Nome da Tarefa:"))
        self.txtTask.setPlaceholderText(_translate("MainWindow", "Tarefa"))
        self.btnAddTask.setText(_translate("MainWindow", "Adicionar Tarefa ➕"))
        self.btnDeleteTask.setText(_translate("MainWindow", "Remover Tarefa  🗑️"))
        self.btnCleanTaskList.setText(_translate("MainWindow", "Limpar Lista de Tarefas"))
        self.btnEditTask.setText(_translate("MainWindow", "Editar Tarefa ✎ "))
        self.taskList.setSortingEnabled(False)
        self.lblTimer.setText(_translate("MainWindow", "25:00"))
        self.label_2.setText(_translate("MainWindow", "Pomodoro"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.label_3.setText(_translate("MainWindow", "Matriz de Eisenhower"))
        self.label_4.setText(_translate("MainWindow", "Calendário"))
        self.label_5.setText(_translate("MainWindow", "Desempenho"))
