# Form implementation generated from reading ui file 'ui/registrar.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1221, 716)
        MainWindow.setMinimumSize(QtCore.QSize(1221, 716))
        MainWindow.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(450, 650))
        self.frame.setStyleSheet("background-color: white;\n"
"border-radius: 60px;\n"
"border: 2px solid rgba(0, 0, 0, 25);\n"
"padding: 10px;")
        self.frame.setObjectName("frame")
        self.txtFundo2 = QtWidgets.QLineEdit(parent=self.frame)
        self.txtFundo2.setEnabled(False)
        self.txtFundo2.setGeometry(QtCore.QRect(60, 410, 321, 41))
        self.txtFundo2.setStyleSheet("border-color: #30426b;\n"
"border-radius: 10px;\n"
"background:transparent;")
        self.txtFundo2.setObjectName("txtFundo2")
        self.btnRegister = QtWidgets.QPushButton(parent=self.frame)
        self.btnRegister.setGeometry(QtCore.QRect(90, 540, 271, 51))
        self.btnRegister.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnRegister.setStyleSheet("QPushButton {\n"
"    background-color: rgb(48, 66, 107);\n"
"    color: white;\n"
"    font: 20pt \"helvetica\";\n"
"    border-radius: 20px;\n"
"    font-weight: bold;\n"
"padding:0px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: rgb(48, 66, 107);\n"
"    background-color:white;\n"
"    color:rgb(48, 66, 107);\n"
"\n"
"}\n"
"")
        self.btnRegister.setObjectName("btnRegister")
        self.widget_3 = QtWidgets.QWidget(parent=self.frame)
        self.widget_3.setGeometry(QtCore.QRect(70, 110, 41, 41))
        self.widget_3.setStyleSheet("border-image: url(:/img/login/user.png);\n"
"background:transparent;\n"
"margin: 4px;")
        self.widget_3.setObjectName("widget_3")
        self.txtNome = QtWidgets.QLineEdit(parent=self.frame)
        self.txtNome.setGeometry(QtCore.QRect(120, 120, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtNome.setFont(font)
        self.txtNome.setStyleSheet("background:transparent;\n"
"border: none;\n"
"padding: 0px;")
        self.txtNome.setText("")
        self.txtNome.setObjectName("txtNome")
        self.txtFundo1 = QtWidgets.QLineEdit(parent=self.frame)
        self.txtFundo1.setEnabled(False)
        self.txtFundo1.setGeometry(QtCore.QRect(60, 110, 321, 41))
        self.txtFundo1.setStyleSheet("border-radius: 10px;\n"
"border-color: #30426b;\n"
"background:transparent;")
        self.txtFundo1.setObjectName("txtFundo1")
        self.txtSenha = QtWidgets.QLineEdit(parent=self.frame)
        self.txtSenha.setGeometry(QtCore.QRect(120, 420, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtSenha.setFont(font)
        self.txtSenha.setStyleSheet("background:transparent;\n"
"border: none;\n"
"padding: 0px;")
        self.txtSenha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtSenha.setObjectName("txtSenha")
        self.widget_4 = QtWidgets.QWidget(parent=self.frame)
        self.widget_4.setGeometry(QtCore.QRect(70, 410, 41, 41))
        self.widget_4.setStyleSheet("border-image: url(:/img/login/senha.png);\n"
"background:transparent;\n"
"margin:5px;")
        self.widget_4.setObjectName("widget_4")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(100, 600, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.label_2.setStyleSheet("color: #30426b;\n"
"font: 8pt \"Helvetica\";\n"
"border: none;\n"
"padding: 0px")
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.btnLogin = QtWidgets.QPushButton(parent=self.frame)
        self.btnLogin.setGeometry(QtCore.QRect(190, 600, 41, 23))
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnLogin.setStyleSheet("color:#30426b;\n"
"background:transparent;\n"
"padding: 0px;\n"
"border-color:white;\n"
"font: 9pt \"helvetica\";\n"
"font-weight:bold;\n"
"")
        self.btnLogin.setObjectName("btnLogin")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(140, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("helvetica")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #30426b;\n"
"padding: 0px;\n"
"font: 16pt \"helvetica\";\n"
"border:none;\n"
"background:transparent;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(120, 50, 211, 41))
        font = QtGui.QFont()
        font.setFamily("helvetica")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #30426b;\n"
"font: 22pt \"helvetica\";\n"
"font-weight:bold;\n"
"padding:0px;\n"
"border:none;\n"
"background:transparent;")
        self.label_4.setObjectName("label_4")
        self.txtEmail = QtWidgets.QLineEdit(parent=self.frame)
        self.txtEmail.setGeometry(QtCore.QRect(120, 180, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtEmail.setFont(font)
        self.txtEmail.setStyleSheet("background:transparent;\n"
"border: none;\n"
"padding: 0px;")
        self.txtEmail.setText("")
        self.txtEmail.setObjectName("txtEmail")
        self.widget_5 = QtWidgets.QWidget(parent=self.frame)
        self.widget_5.setGeometry(QtCore.QRect(70, 170, 41, 41))
        self.widget_5.setStyleSheet("border-image: url(:/img/cadastro/email.png);\n"
"background:transparent;\n"
"margin: 5px;")
        self.widget_5.setObjectName("widget_5")
        self.txtFundo1_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.txtFundo1_2.setEnabled(False)
        self.txtFundo1_2.setGeometry(QtCore.QRect(60, 170, 321, 41))
        self.txtFundo1_2.setStyleSheet("border-radius: 10px;\n"
"border-color: #30426b;\n"
"background:transparent;")
        self.txtFundo1_2.setObjectName("txtFundo1_2")
        self.txtMatricula = QtWidgets.QLineEdit(parent=self.frame)
        self.txtMatricula.setGeometry(QtCore.QRect(120, 240, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtMatricula.setFont(font)
        self.txtMatricula.setStyleSheet("background:transparent;\n"
"border: none;\n"
"padding: 0px;")
        self.txtMatricula.setText("")
        self.txtMatricula.setObjectName("txtMatricula")
        self.widget_6 = QtWidgets.QWidget(parent=self.frame)
        self.widget_6.setGeometry(QtCore.QRect(70, 230, 41, 41))
        self.widget_6.setStyleSheet("border-image: url(:/img/cadastro/matricula.png);\n"
"background:transparent;\n"
"margin: 5px;")
        self.widget_6.setObjectName("widget_6")
        self.txtFundo1_3 = QtWidgets.QLineEdit(parent=self.frame)
        self.txtFundo1_3.setEnabled(False)
        self.txtFundo1_3.setGeometry(QtCore.QRect(60, 230, 321, 41))
        self.txtFundo1_3.setStyleSheet("border-radius: 10px;\n"
"border-color: #30426b;\n"
"background:transparent;")
        self.txtFundo1_3.setObjectName("txtFundo1_3")
        self.txtCurso = QtWidgets.QLineEdit(parent=self.frame)
        self.txtCurso.setGeometry(QtCore.QRect(120, 300, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtCurso.setFont(font)
        self.txtCurso.setStyleSheet("background:transparent;\n"
"border: none;\n"
"padding: 0px;")
        self.txtCurso.setText("")
        self.txtCurso.setObjectName("txtCurso")
        self.txtFundo1_4 = QtWidgets.QLineEdit(parent=self.frame)
        self.txtFundo1_4.setEnabled(False)
        self.txtFundo1_4.setGeometry(QtCore.QRect(60, 290, 321, 41))
        self.txtFundo1_4.setStyleSheet("border-radius: 10px;\n"
"border-color: #30426b;\n"
"background:transparent;")
        self.txtFundo1_4.setObjectName("txtFundo1_4")
        self.widget_7 = QtWidgets.QWidget(parent=self.frame)
        self.widget_7.setGeometry(QtCore.QRect(70, 290, 41, 41))
        self.widget_7.setStyleSheet("border-image: url(:/img/cadastro/curso.png);\n"
"background:transparent;")
        self.widget_7.setObjectName("widget_7")
        self.txtFundo1_5 = QtWidgets.QLineEdit(parent=self.frame)
        self.txtFundo1_5.setEnabled(False)
        self.txtFundo1_5.setGeometry(QtCore.QRect(60, 350, 321, 41))
        self.txtFundo1_5.setStyleSheet("border-radius: 10px;\n"
"border-color: #30426b;\n"
"background:transparent;")
        self.txtFundo1_5.setObjectName("txtFundo1_5")
        self.widget_8 = QtWidgets.QWidget(parent=self.frame)
        self.widget_8.setGeometry(QtCore.QRect(70, 350, 41, 41))
        self.widget_8.setStyleSheet("border-image: url(:/img/cadastro/celular.png);\n"
"background:transparent;\n"
"margin: 5px;")
        self.widget_8.setObjectName("widget_8")
        self.txtCelular = QtWidgets.QLineEdit(parent=self.frame)
        self.txtCelular.setGeometry(QtCore.QRect(120, 360, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtCelular.setFont(font)
        self.txtCelular.setStyleSheet("background:transparent;\n"
"border: none;\n"
"padding: 0px;")
        self.txtCelular.setText("")
        self.txtCelular.setObjectName("txtCelular")
        self.txtFundo2_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.txtFundo2_2.setEnabled(False)
        self.txtFundo2_2.setGeometry(QtCore.QRect(60, 470, 321, 41))
        self.txtFundo2_2.setStyleSheet("border-color: #30426b;\n"
"border-radius: 10px;\n"
"background:transparent;")
        self.txtFundo2_2.setObjectName("txtFundo2_2")
        self.txtConfirmSenha = QtWidgets.QLineEdit(parent=self.frame)
        self.txtConfirmSenha.setGeometry(QtCore.QRect(120, 480, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtConfirmSenha.setFont(font)
        self.txtConfirmSenha.setStyleSheet("background:transparent;\n"
"border: none;\n"
"padding: 0px;")
        self.txtConfirmSenha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtConfirmSenha.setObjectName("txtConfirmSenha")
        self.widget_10 = QtWidgets.QWidget(parent=self.frame)
        self.widget_10.setGeometry(QtCore.QRect(70, 470, 41, 41))
        self.widget_10.setStyleSheet("border-image: url(:/img/login/senha.png);\n"
"background:transparent;\n"
"margin:5px;")
        self.widget_10.setObjectName("widget_10")
        self.txtFundo1_4.raise_()
        self.txtFundo1_3.raise_()
        self.txtFundo1_2.raise_()
        self.txtFundo2.raise_()
        self.btnRegister.raise_()
        self.txtFundo1.raise_()
        self.txtNome.raise_()
        self.widget_3.raise_()
        self.txtSenha.raise_()
        self.widget_4.raise_()
        self.label_2.raise_()
        self.btnLogin.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.txtEmail.raise_()
        self.widget_5.raise_()
        self.txtMatricula.raise_()
        self.widget_6.raise_()
        self.txtCurso.raise_()
        self.widget_7.raise_()
        self.txtFundo1_5.raise_()
        self.widget_8.raise_()
        self.txtCelular.raise_()
        self.txtFundo2_2.raise_()
        self.txtConfirmSenha.raise_()
        self.widget_10.raise_()
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1221, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txtNome, self.txtEmail)
        MainWindow.setTabOrder(self.txtEmail, self.txtMatricula)
        MainWindow.setTabOrder(self.txtMatricula, self.txtCurso)
        MainWindow.setTabOrder(self.txtCurso, self.txtCelular)
        MainWindow.setTabOrder(self.txtCelular, self.txtSenha)
        MainWindow.setTabOrder(self.txtSenha, self.txtConfirmSenha)
        MainWindow.setTabOrder(self.txtConfirmSenha, self.btnRegister)
        MainWindow.setTabOrder(self.btnRegister, self.btnLogin)
        MainWindow.setTabOrder(self.btnLogin, self.txtFundo1)
        MainWindow.setTabOrder(self.txtFundo1, self.txtFundo1_2)
        MainWindow.setTabOrder(self.txtFundo1_2, self.txtFundo1_3)
        MainWindow.setTabOrder(self.txtFundo1_3, self.txtFundo1_4)
        MainWindow.setTabOrder(self.txtFundo1_4, self.txtFundo1_5)
        MainWindow.setTabOrder(self.txtFundo1_5, self.txtFundo2)
        MainWindow.setTabOrder(self.txtFundo2, self.txtFundo2_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registrar"))
        self.frame.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btnRegister.setText(_translate("MainWindow", "Registrar"))
        self.txtNome.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.txtSenha.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.label_2.setText(_translate("MainWindow", "Já possui conta?"))
        self.btnLogin.setText(_translate("MainWindow", "Entrar"))
        self.label_3.setText(_translate("MainWindow", "Crie sua conta e"))
        self.label_4.setText(_translate("MainWindow", "Comece agora"))
        self.txtEmail.setPlaceholderText(_translate("MainWindow", "Email"))
        self.txtMatricula.setPlaceholderText(_translate("MainWindow", "Matrícula"))
        self.txtCurso.setPlaceholderText(_translate("MainWindow", "Curso"))
        self.txtCelular.setPlaceholderText(_translate("MainWindow", "Celular"))
        self.txtConfirmSenha.setPlaceholderText(_translate("MainWindow", "Confirmar Senha"))
