# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1152, 648)
        MainWindow.setMinimumSize(QtCore.QSize(1152, 648))
        MainWindow.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(800, 400))
        self.frame.setStyleSheet("background-color: white;\n"
"border-radius: 60px;\n"
"border: 2px solid rgba(0, 0, 0, 25);\n"
"padding: 10px;")
        self.frame.setObjectName("frame")
        self.widget_2 = QtWidgets.QWidget(parent=self.frame)
        self.widget_2.setGeometry(QtCore.QRect(80, 30, 201, 191))
        self.widget_2.setStyleSheet("border-image: url(:/img/logo.png);\n"
"background:transparent;")
        self.widget_2.setObjectName("widget_2")
        self.txtFundo2 = QtWidgets.QLineEdit(parent=self.frame)
        self.txtFundo2.setEnabled(False)
        self.txtFundo2.setGeometry(QtCore.QRect(410, 180, 321, 41))
        self.txtFundo2.setStyleSheet("border-color: #30426b;\n"
"border-radius: 10px;\n"
"background:transparent;")
        self.txtFundo2.setObjectName("txtFundo2")
        self.btnConfirm = QtWidgets.QPushButton(parent=self.frame)
        self.btnConfirm.setGeometry(QtCore.QRect(450, 280, 261, 51))
        self.btnConfirm.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnConfirm.setStyleSheet("QPushButton {\n"
"    background-color: rgb(48, 66, 107);\n"
"    color: white;\n"
"    font: 22pt \"helvetica\";\n"
"    border-radius: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: rgb(48, 66, 107);\n"
"    background-color:white;\n"
"    color:rgb(48, 66, 107);\n"
"\n"
"}\n"
"")
        self.btnConfirm.setObjectName("btnConfirm")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(420, 230, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.label.setStyleSheet("color: #30426b;\n"
"font: 8pt \"Helvetica\";\n"
"border: none;\n"
"padding: 0px")
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.widget_3 = QtWidgets.QWidget(parent=self.frame)
        self.widget_3.setGeometry(QtCore.QRect(420, 110, 41, 41))
        self.widget_3.setStyleSheet("border-image: url(:/img/login/user.png);\n"
"background:transparent;")
        self.widget_3.setObjectName("widget_3")
        self.txtLogin = QtWidgets.QLineEdit(parent=self.frame)
        self.txtLogin.setGeometry(QtCore.QRect(470, 120, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtLogin.setFont(font)
        self.txtLogin.setStyleSheet("background:transparent;\n"
"border: none;\n"
"padding: 0px")
        self.txtLogin.setText("")
        self.txtLogin.setObjectName("txtLogin")
        self.txtFundo1 = QtWidgets.QLineEdit(parent=self.frame)
        self.txtFundo1.setEnabled(False)
        self.txtFundo1.setGeometry(QtCore.QRect(410, 110, 321, 41))
        self.txtFundo1.setStyleSheet("border-radius: 10px;\n"
"border-color: #30426b;\n"
"background:transparent;")
        self.txtFundo1.setObjectName("txtFundo1")
        self.txtSenha = QtWidgets.QLineEdit(parent=self.frame)
        self.txtSenha.setGeometry(QtCore.QRect(470, 190, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtSenha.setFont(font)
        self.txtSenha.setStyleSheet("background:transparent;\n"
"border: none;\n"
"padding: 0px")
        self.txtSenha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtSenha.setObjectName("txtSenha")
        self.widget_4 = QtWidgets.QWidget(parent=self.frame)
        self.widget_4.setGeometry(QtCore.QRect(420, 180, 41, 41))
        self.widget_4.setStyleSheet("border-image: url(:/img/login/senha.png);\n"
"background:transparent;\n"
"margin:5px;")
        self.widget_4.setObjectName("widget_4")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(450, 340, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.label_2.setStyleSheet("color: #30426b;\n"
"font: 8pt \"Helvetica\";\n"
"border: none;\n"
"padding: 0px")
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.btnRegistrar = QtWidgets.QPushButton(parent=self.frame)
        self.btnRegistrar.setGeometry(QtCore.QRect(540, 340, 61, 23))
        self.btnRegistrar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnRegistrar.setStyleSheet("color:#30426b;\n"
"background:transparent;\n"
"padding: 0px;\n"
"border:none;\n"
"font: 9pt \"helvetica\";\n"
"font-weight:bold;\n"
"")
        self.btnRegistrar.setObjectName("btnRegistrar")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(70, 230, 251, 31))
        font = QtGui.QFont()
        font.setFamily("helvetica")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:transparent;\n"
"border:none;\n"
"color:white;\n"
"padding: 0px;\n"
"font: 16pt \"helvetica\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(130, 260, 111, 31))
        font = QtGui.QFont()
        font.setFamily("helvetica")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background:transparent;\n"
"color:white;\n"
"border: none;\n"
"font: 19pt \"helvetica\";\n"
"font-weight:bold;\n"
"padding:0px")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 371, 401))
        self.label_5.setStyleSheet("background-color:rgb(48, 66, 107);\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.lblErro = QtWidgets.QLabel(parent=self.frame)
        self.lblErro.setGeometry(QtCore.QRect(400, 40, 331, 41))
        self.lblErro.setStyleSheet("color:rgb(226, 17, 63);\n"
"background:transparent;\n"
"border-color:white;\n"
"font: 19pt \"helvetica\";\n"
"padding:0px")
        self.lblErro.setText("")
        self.lblErro.setObjectName("lblErro")
        self.label_5.raise_()
        self.widget_2.raise_()
        self.txtFundo2.raise_()
        self.btnConfirm.raise_()
        self.label.raise_()
        self.txtFundo1.raise_()
        self.txtLogin.raise_()
        self.widget_3.raise_()
        self.txtSenha.raise_()
        self.widget_4.raise_()
        self.label_2.raise_()
        self.btnRegistrar.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.lblErro.raise_()
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1152, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.frame.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btnConfirm.setText(_translate("MainWindow", "LOGIN"))
        self.label.setText(_translate("MainWindow", "Esqueceu a senha"))
        self.txtLogin.setPlaceholderText(_translate("MainWindow", "matrícula"))
        self.txtSenha.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.label_2.setText(_translate("MainWindow", "Não possui conta?"))
        self.btnRegistrar.setText(_translate("MainWindow", "Registrar"))
        self.label_3.setText(_translate("MainWindow", "Entre para continuar sua"))
        self.label_4.setText(_translate("MainWindow", "Jornada"))
